/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package yy.defaultfont;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="Tidefaultfont", id="yy.defaultfont")
public class TidefaultfontModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TidefaultfontModule";
    private static String font;
	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TidefaultfontModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
	    font =app.getAppProperties().getString("ti.android.defaultfont",null);
		if (font != null) {
		  // Affects action bar etc
		  TypefaceUtil.overrideFont(app.getApplicationContext(), "SERIF", "Resources/" + font);
		  // Titanium defaults to SANS_SERIF so we need to override that too.
		  TypefaceUtil.overrideFont(app.getApplicationContext(), "SANS_SERIF", "Resources/" + font);
		} else {
		  Log.e(TAG, "No default font found in tiapp.xml: ti.android.defaultfont");
		}

	}
	
	// Properties
	@Kroll.getProperty
	public String getDefaultFont()
	{
		return TidefaultfontModule.font;
	}

}

